const dir = "../Images";

const Images = {
  "logo": require("../Images/logo.png"),
  "background_1": require("../Images/background_1.jpg"),
  "background_2": require("../Images/background_2.jpg"),
  "background_3": require("../Images/background_3.jpg"),
  "background_4": require("../Images/background_4.jpg"),
  "background_5": require("../Images/background_5.jpg"),
  "tableplan_grid": require("../Images/tableplan_grid.png"),
  "default_event_pic": require("../Images/default_event.jpg"),

  "icons": {
    "search": require("../Images/icons/search.png"),
    "event_success": require("../Images/icons/success_icon.png"),
    "back": require("../Images/icons/back.png"),
    "date_picker_icon": require("../Images/icons/date_picker_icon.png"),
    "time_picker_icon": require("../Images/icons/time_picker_icon.png"),
    "valid": require("../Images/icons/green_check.png"),
    "invalid": require("../Images/icons/red_cross.png"),
    "eye": require("../Images/icons/eye.png"),
    "fb_logo": require("../Images/icons/fb_logo.png"),
    "qr_code": require("../Images/icons/qrcode.png"),
    "delete_invite_icon": require("../Images/icons/delete.png"),
    "menu": require("../Images/icons/menu.png"),
    "menu_white": require("../Images/icons/menu_white.png"),
    "pick_image": require("../Images/icons/pick_image_icon.png"),
    "plus_icon": require("../Images/icons/plus_icon.png"),
    "icon_back_drawer": require("../Images/icons/icon_back_drawer.png"),
    "guest": require("../Images/icons/guest.png"),
    "seating_plan": require("../Images/icons/seating_plan.png"),
    "media": require("../Images/icons/media.png"),
    "chat": require("../Images/icons/chat.png"),
    "pot": require("../Images/icons/pot.png"),
    "guest_actif": require("../Images/icons/guest_actif.png"),
    "seating_plan_actif": require("../Images/icons/seating_plan_actif.png"),
    "media_actif": require("../Images/icons/media_actif.png"),
    "chat_actif": require("../Images/icons/chat_actif.png"),
    "pot_actif": require("../Images/icons/pot_actif.png"),
    "emoji_picker": require("../Images/icons/smiley_button.png"),
    "send_message": require("../Images/icons/send_message.png"),
    "table_pin": require("../Images/icons/table_pin.png"),
    "back_arrow": require("../Images/icons/back_arrow.png"),
    "like": require("../Images/icons/like.png"),
    "cancel": require("../Images/icons/cancel.png"),
    "comment": require("../Images/icons/comments.png"),
    "like_actif": require("../Images/icons/like_actif.png"),
    "erase_photo": require("../Images/icons/erase_photo.png"),
    "participating_icon" : require("../Images/icons/participating_icon.png"),
    "manage_event" : require("../Images/icons/manage.png"),
    "picker_icon" : require("../Images/icons/picker_icon.png"),
    "logout_icon" : require("../Images/icons/logout.png"),
    "edit_user" : require("../Images/icons/settings.png"),
    "context_menu" : require("../Images/icons/context_menu_icon.png"),
    "filters" : require("../Images/icons/filter.png"),
    "close" : require("../Images/icons/close_white.png"),
    "loc_grey" : require("../Images/icons/loc_grey.png"),
    "loc_blue" : require("../Images/icons/loc_blue.png"),
    "restaurant_icon" : require("../Images/icons/restaurant.png"),
    "applied_filter" : require("../Images/icons/applied_filter.png"),
    "dashboard" : require("../Images/icons/dashboard.png"),
    "dashboard_actif" : require("../Images/icons/dashboard_actif.png"),
    "dash_date" : require("../Images/icons/dash_date.png"),
    "dash_guest" : require("../Images/icons/dash_guest.png"),
    "dash_location" : require("../Images/icons/dash_location.png"),
    "dash_hour" : require("../Images/icons/dash_hour.png"),
    "dash_pot" : require("../Images/icons/dash_pot.png"),
    "dash_goto" : require("../Images/icons/dash_goto.png"),
    "pot_total" : require("../Images/icons/pot_total.png"),
    "location" : require("../Images/icons/location.png"),
    "add_black" : require("../Images/icons/add_black.png"),
    "cancel" : require("../Images/icons/cancel.png"),
    "clear_img" : require("../Images/icons/delete.png"),
    "add_guest" : require("../Images/icons/add_guest.png"),
    "play_button" : require("../Images/icons/play_button.png"),
    "settings_active" : require("../Images/icons/settings_active.png"),
    "flag_en" : require("../Images/icons/flag_en.png"),
    "flag_fr" : require("../Images/icons/flag_fr.png"),
    "flag_es" : require("../Images/icons/flag_es.png"),
    "download_fa" : require("../Images/icons/download_fa.png"),
    "share_fa" : require("../Images/icons/share_fa.png"),
    "provider" : require("../Images/icons/provider.png"),
    "provider_actif" : require("../Images/icons/provider_actif.png"),
    "coins" : require("../Images/icons/coins.png"),
    "group" : require("../Images/icons/group.png"),
    "phone" : require("../Images/icons/phone.png"),
    "reply" : require("../Images/icons/reply.png"),
    "rating_full" : require("../Images/icons/rating_full.png"),
    "rating_empty" : require("../Images/icons/rating_empty.png"),
    "thumbs_up" : require("../Images/icons/thumbs_up.png"),
    "thumbs_up_active" : require("../Images/icons/thumbs_up_active.png"),
    "thumbs_down" : require("../Images/icons/thumbs_down.png"),
    "thumbs_down_active" : require("../Images/icons/thumbs_down_active.png"),
    "discount" : require("../Images/icons/discount.png"),
  }
}

export default Images;
