# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'miiting' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for miiting
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
    pod 'RNSVG', :path => '../node_modules/react-native-svg'
    pod 'react-native-camera', path: '../node_modules/react-native-camera'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'Picker', :path => '../node_modules/react-native-picker'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'miitingTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end

  ## Fix for XCode 12.5 beta
  find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
  "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
